### ISSUE TITLE
Add `overwrite` argument to saving box

### ISSUE THREAD

**Issue by rmatsum836** [MaginnGroup/mosdef_cassandra#38]
**Is your feature request related to a problem? Please describe.**
In `write_configs`, the system boxes are saved to xyz files.  If we are re-running the same script that contains `mc.run`, then the script will error out due to trying to overwrite these xyz files.

**Describe the solution you'd like**
In `write_configs` add the optional argument `overwrite=True` so that the box xyz file will get overwritten if it already exists.

**Comment by rsdefever** [comment]
I don't think the default behavior should be to overwrite. How about adding an optional keyword argument to `mc.run`?
