### ISSUE TITLE
NVT example in docs fails in production environment

### ISSUE THREAD

**Issue by rsdefever** [MaginnGroup/mosdef_cassandra#78]
**Bug summary**

* The example NVT [here](https://mosdef-cassandra.readthedocs.io/en/latest/getting_started/examples.html) fails with the following error:

```
ModuleNotFoundError: No module named 'mosdef_cassandra.utils.get_files'
```

* The title is also now incorrect, it says NVT simulation of methane but it is in fact of SPC/E water. 
* IMO, we should also start with a more simple example. I don't like using the `get_ff_path` and `get_mol2_path` in the first example on the website. We should start as simple as possible.

This change occurred when the NVT example was changed to SPC/E water as a test on the `angle_style=fixed` option (#72). 

**Desired behavior**

The fix should replace the NVT example with the original example of a simulation of methane. The SPC/E example can be included, but separately. Docs should be added to demonstrate an NVT simulation of water (this is basic functionality that we should demonstrate). 

**Software versions**

Please include the following details:

- Operating system and version
- `Cassandra` version `1.2.5`
- `mosdef_cassandra` version `0.1.2`
- `mbuild` version `0.10.8`
- `foyer` version `0.7.6`

**Comment by rmatsum836** [comment]
As for `get_ff_path` and `get_mol2_path`, would you like for these files to exist in the `examples` directory for simplification?

**Comment by rsdefever** [comment]
@rmatsum836 see what I did in #80. `get_ff_path` and `get_mol2_path` are fine, I just don't want to confuse (particularly Python novices) off the bat with extra functions. I also removed the `literal include` from the docs and copy-pasted the examples so that (1) they don't need to be inside functions and (2) the `custom_args`/`default_args` issue doesn't show up in the examples.
